# This workflow will build 'webapp' folder, test and deploy to github pages on branch gh-pages
# For more information see:
#   - https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#   - https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy Webapp

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./webapp
      run: yarn install --frozen-lockfile

    - name: Test
      working-directory: ./webapp
      run: yarn test
      
    - name: Build 🔧
      working-directory: ./webapp
      run: yarn build
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./webapp/build # The folder which will be deployed.
